In [16]:
#Import the pandas libraru
import pandas as pd

In [17]:
#Import csv file
employees = pd.read_csv(r"Employee.csv")
#Visualise the data set
employees.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [18]:
#Basic Data Understanding
# 1
grouped_employees = employees.groupby("PaymentTier")#Group the columns by the PaymentTier column
grouped_employees.count()#count() tells you how many values there are in each row

,Education,JoiningYear,City,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
PaymentTier,,,,,,,,
1,243,243,243,243,243,243,243,243
2,918,918,918,918,918,918,918,918
3,3492,3492,3492,3492,3492,3492,3492,3492

In [19]:
#2
grouped_gender = employees.groupby("Gender")
grouped_gender.count()

,Education,JoiningYear,City,PaymentTier,Age,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
Gender,,,,,,,,
Female,1875,1875,1875,1875,1875,1875,1875,1875
Male,2778,2778,2778,2778,2778,2778,2778,2778

In [20]:
#3
grouped_education = employees.groupby("Education").agg({"Age":["mean"]})#Group the columns by education and then finds the average age of each level of education
grouped_education

                 Age
                mean
Education
Bachelors  29.422938
Masters    29.290951
PHD        29.296089

In [21]:
#4
#Groups the columns by the year the employees joined and then gives the min,max and average of experience for each year
grouped_joiningYear = employees.groupby("JoiningYear").agg({"ExperienceInCurrentDomain":["min","max","mean"]})
grouped_joiningYear

            ExperienceInCurrentDomain
                                  min max      mean
JoiningYear
2012                                0   7  3.057540
2013                                0   6  2.983558
2014                                0   7  2.974249
2015                                0   7  2.756722
2016                                0   7  2.853333
2017                                0   6  2.892599
2018                                0   6  2.855586

In [22]:
#Intermediate Aggregations
#5
grouped_city = employees.groupby("City").agg({"EverBenched":["sum"]})#Groups by the city and adds all the values of the everbenched column
grouped_city

                                                 EverBenched
                                                         sum
City
Bangalore  NoNoNoNoNoNoNoNoNoNoYesNoYesNoNoNoNoNoNoNoNoNo...
New Delhi  NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoN...
Pune       NoYesNoNoYesNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoN...

In [23]:
#6
#Group by two columns, gender and paymentTier and then finds the average of age and experience for both male and female and then each payment tier
grouped_gender_payment = employees.groupby(["Gender","PaymentTier"]).agg({"Age":["mean"],"ExperienceInCurrentDomain":["mean"]})
grouped_gender_payment

                          Age ExperienceInCurrentDomain
                         mean                      mean
Gender PaymentTier
Female 1            28.893130                  2.687023
       2            29.259504                  2.882645
       3            29.559263                  2.915716
Male   1            30.410714                  2.848214
       2            29.035144                  2.936102
       3            29.374416                  2.917552

In [24]:
#7
#Groups by education and finds which education level has the highest turnover rate, since 1 means that the employee left and 0 means that they stayed
#I used max to get all the 1's for each education level and then used count to see which education level has the most amount of 1's, therefore the highest turnover rate
grouped_educationlvl = employees.groupby("Education").agg({"LeaveOrNot":["max","count"]})
grouped_educationlvl

          LeaveOrNot
                 max count
Education
Bachelors          1  3601
Masters            1   873
PHD                1   179

In [25]:
#8
#Grouping by two columns to find the middle most values for age and experience for both male and female and each education level
grouped_gender_education = employees.groupby(["Gender","Education"]).agg({"Age":["median"],"ExperienceInCurrentDomain":["median"]})
grouped_gender_education

                    Age ExperienceInCurrentDomain
                 median                    median
Gender Education
Female Bachelors   28.0                       3.0
       Masters     28.0                       2.0
       PHD         28.0                       3.0
Male   Bachelors   28.0                       3.0
       Masters     28.0                       3.0
       PHD         27.0                       3.0

In [26]:
#Advanced Analysis
#9
#Comparing the three payment tiers with each level of education
#Essentially looking at the amount of employees in each education level and payment tier. Eg.How many employees have a bachelor's degree that are in payment tier 1. 
cross_tab_employees = pd.crosstab(employees["Education"],employees["PaymentTier"])
cross_tab_employees

PaymentTier    1    2     3
Education
Bachelors    173  543  2885
Masters       56  355   462
PHD           14   20   145

In [27]:
#10
#Groups the columns by joiningYear and finds the total of the everbenched column for each year
grouped = employees.groupby("JoiningYear").agg({"EverBenched":"sum"})
grouped

                                                   EverBenched
JoiningYear
2012         NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYe...
2013         NoYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoN...
2014         NoNoNoNoNoYesNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNo...
2015         NoNoYesNoNoNoNoNoNoNoNoYesNoNoNoYesNoNoNoNoNoN...
2016         NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNo...
2017         NoYesNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNo...
2018         YesNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoN...

In [28]:
#10
#Finds the average experience for each year
grouped2 = employees.groupby("JoiningYear").agg({"ExperienceInCurrentDomain":["mean"]})
grouped2

            ExperienceInCurrentDomain
                                 mean
JoiningYear
2012                         3.057540
2013                         2.983558
2014                         2.974249
2015                         2.756722
2016                         2.853333
2017                         2.892599
2018                         2.855586

In [29]:
#11
#Groups by city and education level and finds the minimum and maximum age for each education level in that city
group = employees.groupby(["City","Education"]).agg({"Age":["min","max"]})
group

                    Age
                    min max
City      Education
Bangalore Bachelors  22  41
          Masters    24  41
          PHD        23  41
New Delhi Bachelors  22  41
          Masters    22  41
          PHD        22  41
Pune      Bachelors  22  41
          Masters    22  41
          PHD        24  41

In [30]:
#12
#Groups by paymentTier and finds the minimum, maximum and average values of the leaveOrNot column for each payment tier.
group2 = employees.groupby("PaymentTier").agg({"LeaveOrNot":["min","max","mean"]})
group2

            LeaveOrNot
                   min max      mean
PaymentTier
1                    0   1  0.366255
2                    0   1  0.599129
3                    0   1  0.275200