In [1]:
import pandas as pd 
import plotly.express as px
import seaborn as sns

mpg = sns.load_dataset('mpg')

mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [2]:
fig = px.scatter(mpg,
                 x='horsepower',
                 y='mpg',
                 hover_data=['name'],
                 color='origin',
                 size = 'cylinders',
                 title= 'vehicle mpg by horsepower',
                 labels={'horsepower':'Horsepower', 'mpg':'Miles per gallon',})

fig.show()

In [3]:
import pandas as pd
import seaborn as sns 
import plotly.express as px

tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
import pandas as pd
import seaborn as sns
import plotly.express as px

p = sns.load_dataset('penguins')
p.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [5]:
import pandas as pd
import seaborn as sns
import plotly.express as px

p = sns.load_dataset('penguins')

fig = px.box(
    p,
    x='species',
    y='body_mass_g',
    color =  'island',
    hover_data=['sex','bill_length_mm','flipper_length_mm','body_mass_g'],
    title='Penguin characteristics by species',
)
fig.show()